### PR TITLE
ci: Update outdated external testing deps

### LINKED ISSUE #649: CI is failing probably due to missing guestbook images
### Description

Since a few days, our acceptance tests are unstable. I first suspected external dependencies like charts from elastic.co but it seems more like the heptio images for the guestbook disappeared:

Image

/cc @the-technat @blakepettersson @onematchfox @crenshaw-dev 

Link to discussion in **#argo-cd-contributors** slack:
> Image
> 
> https://cloud-native.slack.com/archives/C020XM04CUW/p1747231505846999

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by mkilchhofer**
Fixes #649 

Related to:
- https://github.com/argoproj/argocd-example-apps/pull/385

### CODE REVIEW

File: argocd/resource_argocd_application_test.go [hunk 1]
```diff
@@ -2347,9 +2347,25 @@ resource "argocd_application" "multiple_sources" {
     project = "default" 
 	
 	source {
-		repo_url        = "https://helm.elastic.co"
-		chart           = "elasticsearch"
-		target_revision = "8.5.1"
```
Comment (mkilchhofer) [inline argocd/resource_argocd_application_test.go:2352]: 2.5years old

```bash
$ curl --silent https://helm.elastic.co/index.yaml| yq -e .entries.elasticsearch | head
- apiVersion: v1
  appVersion: 8.5.1
  created: "2022-11-16T15:16:41.757914136Z" # <--------------------- see
  description: Official Elastic helm chart for Elasticsearch
  digest: 8a5e70ec72dc480c8a01b079bf7240722da7d017f5683178e23a745d418448ba
  home: https://github.com/elastic/helm-charts
  icon: https://helm.elastic.co/icons/elasticsearch.png
  maintainers:
    - email: helm-charts@elastic.co
      name: Elastic
```

**Review by the-technat — APPROVED** [review]
Thanks for digging into this!
